## Working Papers

- **Selling Supplemental Information (Draft comming soon)**  
  **Abstract:** I consider an environment in which a decision maker faces uncertainty and privately holds information in the form of a signal about the true state of the world. The decision maker purchases additional information from a data broker before receiving the signal realization.  I characterize the data broker’s optimal selling mechanism, which involves screening over all possible signals. I allow the space of all signals the data broker can sell to be arbitrarily correlated with the signal the decision maker owns. This plays a key role in designing the optimal menu. In the binary-action setting, the data broker extracts the efficient surplus by offering a distinct binary signal for each type. Moreover, this result holds even when the broker does not know the prior distribution over states. In more general environments, I provide conditions on the payoff structure and the decision maker’s type space under which the data broker extracts the efficient surplus. I discuss scenarios in which efficient-surplus extraction is not possible.


## Work in Progress

- **Consumer Privacy And Personalized Product Design**  
- **Complementary Products and Information Sharing**

## Pre-Phd Research

- **[Dynamic Implications of Wealth–Leisure Nexus](https://repository.bilkent.edu.tr/server/api/core/bitstreams/c95a4bbd-732d-47ec-b586-e6fe307af9b0/content){target="_blank"}**  
  *July, 2022*

